project:
  type: book

book:
  title: "Bass Real Analysis Solutions"
  author: "Jae-Yun Lee"
  date: "2026. 7. 2."

  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html


  chapters:
    - index.qmd
    - about.qmd
    - part: "Chapter 2"
      chapters:
        - chapter-2/exercise-2-1.qmd
        - chapter-2/exercise-2-2.qmd
        - chapter-2/exercise-2-3.qmd
        - chapter-2/exercise-2-4.qmd
        - chapter-2/exercise-2-5.qmd
        - chapter-2/exercise-2-6.qmd
        - chapter-2/exercise-2-7.qmd
        - chapter-2/exercise-2-8.qmd
        - chapter-2/exercise-2-9.qmd
    - part: "Chapter 3"
      chapters:
        - chapter-3/exercise-3-1.qmd
        - chapter-3/exercise-3-2.qmd
        - chapter-3/exercise-3-3.qmd
        - chapter-3/exercise-3-4.qmd
        - chapter-3/exercise-3-5.qmd
        - chapter-3/exercise-3-6.qmd
        - chapter-3/exercise-3-7.qmd
        - chapter-3/exercise-3-8.qmd
        - chapter-3/exercise-3-9.qmd
        - chapter-3/exercise-3-10.qmd
    - part: "Chapter 4"
      chapters:
        - chapter-4/exercise-4-1.qmd
        - chapter-4/exercise-4-2.qmd
        - chapter-4/exercise-4-3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: false
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt